"""Add User.validated_on property

Revision ID: 11932b6088a1
Revises: 455a81da0597
Create Date: 2015-06-09 14:32:26.209713

"""

# revision identifiers, used by Alembic.
revision = '11932b6088a1'
down_revision = '455a81da0597'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('validated_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'validated_on')
    ### end Alembic commands ###
