"""persona_blogs

Revision ID: 28524568cc6e
Revises: 3281ffd0f165
Create Date: 2015-06-24 17:05:25.710968

"""

# revision identifiers, used by Alembic.
revision = '28524568cc6e'
down_revision = '3281ffd0f165'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs_followed',
    sa.Column('follower_id', sa.String(length=32), nullable=True),
    sa.Column('followee_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['identity.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['identity.id'], )
    )
    op.drop_table('movements_followed')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movements_followed',
    sa.Column('persona_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('movement_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], [u'movement.id'], name=u'movements_followed_movement_id_fkey'),
    sa.ForeignKeyConstraint(['persona_id'], [u'persona.id'], name=u'movements_followed_persona_id_fkey')
    )
    op.drop_table('blogs_followed')
    ### end Alembic commands ###
