"""Add mma unique constraint

Revision ID: 2863e5110a5f
Revises: 597b52a2ae1f
Create Date: 2015-07-11 20:35:00.829499

"""

# revision identifiers, used by Alembic.
revision = '2863e5110a5f'
down_revision = '597b52a2ae1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_mma_uc', 'movementmember_association', ['movement_id', 'persona_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_mma_uc', 'movementmember_association', type_='unique')
    ### end Alembic commands ###
