"""Create subclasses for mindset

Revision ID: 3281ffd0f165
Revises: 33bd241ebac1
Create Date: 2015-06-18 19:11:11.684575

"""

# revision identifiers, used by Alembic.
revision = '3281ffd0f165'
down_revision = '33bd241ebac1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mindset', sa.Column('other_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('fk_dialogue_other', 'mindset', 'identity', ['other_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_dialogue_other', 'mindset', type_='foreignkey')
    op.drop_column('mindset', 'other_id')
    ### end Alembic commands ###
