"""mindspace

Revision ID: 34be968b93cb
Revises: 421f8cdf6e1d
Create Date: 2015-05-18 17:33:05.562744

"""

# revision identifiers, used by Alembic.
revision = '34be968b93cb'
down_revision = '421f8cdf6e1d'

from alembic import op
import sqlalchemy as sa

import logging


def upgrade():
    #  commands auto generated by Alembic - please adjust! #
    op.add_column('identity', sa.Column('mindspace_id', sa.String(length=32), nullable=True))
    op.create_foreign_key('fk_mindspace_id', 'identity', 'starmap', ['mindspace_id'], ['id'])

    logging.warning("\n\nPlease run `python -m migrations_extra.mindspace_upgrade` to execute ORM dependent upgrades.\n\n")
    #  end Alembic commands #


def downgrade():
    #  commands auto generated by Alembic - please adjust! #
    op.drop_constraint('fk_mindspace_id', 'identity', type_='foreignkey')
    op.drop_column('identity', 'mindspace_id')
    #  end Alembic commands #
