"""Count upvotes in db

Revision ID: 37658c28ab52
Revises: c62186adfb
Create Date: 2015-07-22 15:28:43.192717

"""

# revision identifiers, used by Alembic.
revision = '37658c28ab52'
down_revision = 'c62186adfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thought', sa.Column('_upvotes', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thought', '_upvotes')
    ### end Alembic commands ###
