"""Added Thought.comment_count

Revision ID: 3c9df11ca3ee
Revises: 59e9e0eeb351
Create Date: 2015-10-01 12:36:25.975639

"""

# revision identifiers, used by Alembic.
revision = '3c9df11ca3ee'
down_revision = '59e9e0eeb351'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thought', sa.Column('_comment_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thought', '_comment_count')
    ### end Alembic commands ###
