"""Remove vesicle

Revision ID: 41f11e397f3c
Revises: 3c9df11ca3ee
Create Date: 2015-12-08 17:09:01.577193

"""

# revision identifiers, used by Alembic.
revision = '41f11e397f3c'
down_revision = '3c9df11ca3ee'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thought_vesicles')
    op.drop_table('movement_vesicles')
    op.drop_table('percept_vesicles')
    op.drop_table('mindset_vesicles')
    op.drop_table('identity_vesicles')
    op.drop_table('keycrypts')
    op.drop_table('vesicle')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_vesicles',
    sa.Column('identity_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('vesicle_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], [u'identity.id'], name=u'identity_vesicles_identity_id_fkey'),
    sa.ForeignKeyConstraint(['vesicle_id'], [u'vesicle.id'], name=u'identity_vesicles_vesicle_id_fkey')
    )
    op.create_table('mindset_vesicles',
    sa.Column('mindset_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('vesicle_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mindset_id'], [u'mindset.id'], name=u'mindset_vesicles_mindset_id_fkey'),
    sa.ForeignKeyConstraint(['vesicle_id'], [u'vesicle.id'], name=u'mindset_vesicles_vesicle_id_fkey')
    )
    op.create_table('percept_vesicles',
    sa.Column('percept_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('vesicle_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['percept_id'], [u'percept.id'], name=u'percept_vesicles_percept_id_fkey'),
    sa.ForeignKeyConstraint(['vesicle_id'], [u'vesicle.id'], name=u'percept_vesicles_vesicle_id_fkey')
    )
    op.create_table('vesicle',
    sa.Column('_send_attributes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('enc', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('handled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('keycrypt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signature', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], [u'persona.id'], name=u'fk_author_id'),
    sa.PrimaryKeyConstraint('id', name=u'vesicle_pkey')
    )
    op.create_table('keycrypts',
    sa.Column('vesicle_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], [u'persona.id'], name=u'keycrypts_recipient_id_fkey'),
    sa.ForeignKeyConstraint(['vesicle_id'], [u'vesicle.id'], name=u'keycrypts_vesicle_id_fkey')
    )
    op.create_table('movement_vesicles',
    sa.Column('movement_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('vesicle_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movement_id'], [u'movement.id'], name=u'movement_vesicles_movement_id_fkey'),
    sa.ForeignKeyConstraint(['vesicle_id'], [u'vesicle.id'], name=u'movement_vesicles_vesicle_id_fkey')
    )
    op.create_table('thought_vesicles',
    sa.Column('thought_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('vesicle_id', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['thought_id'], [u'thought.id'], name=u'thought_vesicles_thought_id_fkey'),
    sa.ForeignKeyConstraint(['vesicle_id'], [u'vesicle.id'], name=u'thought_vesicles_vesicle_id_fkey')
    )
    ### end Alembic commands ###
