"""empty message

Revision ID: 421f8cdf6e1d
Revises: 2f1b4161b614
Create Date: 2015-05-18 13:09:56.185470

"""

# revision identifiers, used by Alembic.
revision = '421f8cdf6e1d'
down_revision = '2f1b4161b614'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'fk_author_id', 'starmap', type_='foreignkey')
    op.create_foreign_key('fk_identity_id', 'starmap', 'identity', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_identity_id', 'starmap', type_='foreignkey')
    op.create_foreign_key(u'fk_author_id', 'starmap', 'persona', ['author_id'], ['id'])
    ### end Alembic commands ###
