"""Make active_persona an attribute of Persona

Revision ID: 53c66ed4223b
Revises: 11932b6088a1
Create Date: 2015-06-10 15:50:05.739739

"""

# revision identifiers, used by Alembic.
revision = '53c66ed4223b'
down_revision = '11932b6088a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona_association', 'active')
    op.add_column('user', sa.Column('active_persona_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'user', 'persona', ['active_persona_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'active_persona_id')
    op.add_column('persona_association', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
