"""Change mma structure

Revision ID: 597b52a2ae1f
Revises: 51f86c6ede56
Create Date: 2015-07-03 12:15:47.783089

"""

# revision identifiers, used by Alembic.
revision = '597b52a2ae1f'
down_revision = '51f86c6ede56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movementmember_association', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('movementmember_association', 'movement_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('movementmember_association', 'persona_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movementmember_association', 'persona_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('movementmember_association', 'movement_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_column('movementmember_association', 'id')
    ### end Alembic commands ###
