"""Add Thought._blogged

Revision ID: 59e9e0eeb351
Revises: 37658c28ab52
Create Date: 2015-07-22 16:36:53.710247

"""

# revision identifiers, used by Alembic.
revision = '59e9e0eeb351'
down_revision = '37658c28ab52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thought', sa.Column('_blogged', sa.Boolean(), nullable=True, server_default="false"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thought', '_blogged')
    ### end Alembic commands ###
