"""Thoughts.posted_from

Revision ID: 65c1f1d7cd6
Revises: 28524568cc6e
Create Date: 2015-06-24 18:21:38.019946

"""

# revision identifiers, used by Alembic.
revision = '65c1f1d7cd6'
down_revision = '28524568cc6e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thought', sa.Column('posted_from', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thought', 'posted_from')
    ### end Alembic commands ###
