"""Add email prefs

Revision ID: c62186adfb
Revises: 2863e5110a5f
Create Date: 2015-07-14 17:42:50.596210

"""

# revision identifiers, used by Alembic.
revision = 'c62186adfb'
down_revision = '2863e5110a5f'

from alembic import op
import sqlalchemy as sa

from sqlalchemy.sql import expression


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_catchall', sa.Boolean(), nullable=True, server_default="false"))
    op.add_column('user', sa.Column('email_react_follow', sa.Boolean(), nullable=True, server_default="true"))
    op.add_column('user', sa.Column('email_react_mention', sa.Boolean(), nullable=True, server_default="true"))
    op.add_column('user', sa.Column('email_react_private', sa.Boolean(), nullable=True, server_default="true"))
    op.add_column('user', sa.Column('email_react_reply', sa.Boolean(), nullable=True, server_default="true"))
    op.add_column('user', sa.Column('email_system_features', sa.Boolean(), nullable=True, server_default="false"))
    op.add_column('user', sa.Column('email_system_security', sa.Boolean(), nullable=True, server_default="true"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_system_security')
    op.drop_column('user', 'email_system_features')
    op.drop_column('user', 'email_react_reply')
    op.drop_column('user', 'email_react_private')
    op.drop_column('user', 'email_react_mention')
    op.drop_column('user', 'email_react_follow')
    op.drop_column('user', 'email_catchall')
    ### end Alembic commands ###
